### ISSUE TITLE
Error trying to cimpile on Kubuntu 15.10

### ISSUE THREAD

**Issue by finid** [sadhen/KMarkNote#12]
Here's an error I got when trying to build on Kubuntu 15.10.

```
CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```

I tried to point it to the Qt5 installation directory using `-DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/qt5`, but that didn't help.

Any clues?

**Comment by da-liii** [comment]
Make sure you have `extra-cmake-modules`, `qt5-default` installed.

according to:

```
find_package(Qt5 REQUIRED
    Core
    WebKit
    WebKitWidgets
)
find_package(KF5WebKit)
find_package (KF5 REQUIRED COMPONENTS
    I18n
    CoreAddons
    XmlGui
    TextEditor
    KDELibs4Support
)
```

you may find the required package this way, take KF5 TextEditor for example:

```
shenda@debian:~$ apt search kf5 texteditor
Sorting... Done
Full Text Search... Done
libkf5texteditor-dev/unstable,now 5.15.0-1 amd64 [installed]
  provide advanced plain text editing services

libkf5texteditor5/unstable,now 5.15.0-1 amd64 [installed,automatic]
  provide advanced plain text editing services

libkf5texteditor5-dbg/unstable 5.15.0-1 amd64
  provide advanced plain text editing services
```

the package with -dev is usually required, just install it.

**Comment by finid** [comment]
I have ECM from source, so that's taken care of. I'll try your suggestion for Qt5.

**Comment by finid** [comment]
Ok, so I have it installed.

Regarding the installation guide, is the second step for installing the Markdown editor really necessary?  After installing Marketo, I find binaries for `marknoto` and `markpado` in the `$HOME/software/bin` directory, and I can run both applications.

Regarding Markpado, is it supposed to have a live preview tab? I couldn't find one.

**Comment by da-liii** [comment]
1. skip the first step, just do the second step, you will only get markpado installed.
2. click split in the tool bar, you will get the live preview area on the right

**Comment by finid** [comment]
The **Split** button is not in the tool bar by default, so had to add it.

Works very nice. Also added the **Preview** button, which is nice too.
