### ISSUE TITLE
Why two applications in one

### ISSUE THREAD

**Issue by finid** [sadhen/KMarkNote#13]
I'm currently using Atom as my note-taking applications, which works just fine for me. The only issue is it uses too much RAM.

In looking at Marketo, why not just make one it one application with built-in support for Markdown, instead of a separate application called Markpado?

**Comment by da-liii** [comment]
I provide two way:
1. install marknoto and markpado
2. markpado only

in the first option, markpado is needed for people who not only take notes using marknoto but also edit markdown formated file out of the `NOTE DIR`. 

If you dislike it, you may comment `add_subdirectory (markpado)` in the top CMake file.

**Comment by finid** [comment]
It's not that I dislike it, just didn't understand the rationale.

For me, it's easier to take notes using a Markdown-capable editor for the ease of text formatting that it brings to the table
