### ISSUE TITLE
麦库笔记已经可以初步同步，为知笔记还在探索，印象笔记无法登录．

### ISSUE THREAD

**Issue by yzbx** [sadhen/KMarkNote#3]
我想，重心放在为知笔记上应该会好一点．

**Comment by da-liii** [comment]
你可以把写好的代码提交上来

**Comment by yzbx** [comment]
放在分析yzbx->src->sycn_script中，对应三个平台有三个脚本，以麦库笔记为主．后天我回家了，家里没网，同步分析要停一阵子．
